server:
  port: 8082
spring:
  kafka:
    consumer:
      bootstrap-servers: ${kafka_bootstrap}
    producer:
      bootstrap-servers: ${kafka_bootstrap}
  jpa:
    hibernate:
      ddl-auto: create-only
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

